language: c

before_script:
  - ./configure
  - cd build
  - cmake ..
script: make
compiler: gcc
dist: trusty
sudo: true
os: linux

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
    - mpi: openmpi
      addons:
        apt:
          packages:
            - openmpi-bin
            - libopenmpi-dev
    - mpi: mpich
      addons:
        apt:
          packages:
            - mpich
